# .github/workflows/build-android.yml

name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev python3-setuptools python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.33
        pip install buildozer
        # Verify Cython installation
        cython --version

    - name: Create main.py if missing
      run: |
        if [ ! -f main.py ]; then
          cat > main.py << 'EOF'
        #!/usr/bin/env python3
        import os
        import sys
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from PLIN053_bookswap import BookSellingApp
        if __name__ == '__main__':
            BookSellingApp().run()
        EOF
        fi

    - name: Setup buildozer.spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        # Update to modern buildozer.spec format
        sed -i 's/android.arch = .*/android.archs = arm64-v8a/' buildozer.spec || echo "android.archs = arm64-v8a" >> buildozer.spec
        sed -i 's/android.api = .*/android.api = 30/' buildozer.spec || echo "android.api = 30" >> buildozer.spec
        sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec || echo "android.minapi = 21" >> buildozer.spec
        sed -i 's/android.ndk = .*/android.ndk = 25b/' buildozer.spec || echo "android.ndk = 25b" >> buildozer.spec
        sed -i 's/requirements = .*/requirements = python3,kivy/' buildozer.spec || echo "requirements = python3,kivy" >> buildozer.spec
        # Remove deprecated android.sdk line
        sed -i '/android.sdk = /d' buildozer.spec

    - name: Build APK with Buildozer
      run: |
        buildozer android debug --verbose
      env:
        ANDROID_NDK_ROOT: ""
        ANDROID_SDK_ROOT: ""

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: knihomat-apk
        path: bin/*.apk
        retention-days: 30

    - name: Upload buildozer log on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: buildozer-log
        path: .buildozer/android/platform/build-**/build.log
        retention-days: 7
